In [62]:
a=5
print(a)
print("hello")

5
hello


Python

In [3]:
x = 3
y = 3.5


print(type(x))
print(type(y))

<class 'int'>
<class 'float'>


###  Importing Libraries in Python
1.   Importing library (math).
2.   Performing  math operations (Ceiling/Floor/Factorial/GCD).

In [64]:
import math as mt

x = 4.5
y =  5

a = 35
b = 40

print(math.ceil(x))
print(math.floor(x))
print(math.factorial(y))
print(math.gcd(a,b))

5
4
120
5


In [65]:
 a = "NITK"
 b = " MACS Dept"
  
 print(a+b)

NITK CSE Dept


###  **Containers**: Python includes several built-in container to hold the data.

1.   Arrays
2.   Lists
2.   Tuples
3.   Dictionaries
4.   Sets





### Numpy (Numerical Python) : 
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

#### Arrays: 
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
#### Array Operations
1.   Declaring Array
2.   Indentify the type
1.   Accesing Array elements
2.   Printing the last element
3.   Printing the lenght of the array
2.   clearing the Array
6.   Deleting the Array

In [66]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [68]:
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [8]:
print(a[0])

1


In [9]:
print(a[-1])

6


In [10]:
print(len(a))

6


In [69]:
del a

In [70]:
print(a)

NameError: ignored

#### Array Operation (Continued)
1.   Declaring the Array Using Random keyword
2.   Printing the shape of the array
3.   Length of the array
4.   Dimension of the array

In [71]:
import numpy as np
import random

a = np.random.randn(1) # 1dimensional

print(a)
print(a.shape)
print(a.ndim)

[0.15353639]
(1,)
1


In [72]:

b = np.random.randn(2,4) #2 dimensional

print(b)
print(b.shape)
print(b.ndim)

[[ 1.14798215  0.98445983  1.40427595 -0.33166501]
 [-0.46278202 -0.32135031 -0.01090419  0.2290941 ]]
(2, 4)
2


####  Numpy Functions


1.   Ones
2.   Zeros
3.   Full
4.   Identity Matrix


In [15]:
import numpy as np

a = np.ones((3,3))
print(a)
print("")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [16]:
b = np.zeros((3,3))
print(b)
print("")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [73]:
c = np.full((3,3),5)
print(c)
print("")


[[5 5 5]
 [5 5 5]
 [5 5 5]]



In [18]:
d = np.eye((3))
print(d)
print("")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



####  Vectorised Implementation


1.   Addition
1.   Subtraction
2.   Multiplication
2.   Dot Product



In [19]:
import numpy as np

a = np.array([4,2,8,10])
b = np.array([4,10,16,20])

In [20]:
print(a)
print(b)

[ 4  2  8 10]
[ 4 10 16 20]


#### Addition

In [74]:
print(a+b)
c=a+b

[[ 1.30151853  1.13799622  1.55781234 -0.17812862]
 [-0.30924563 -0.16781392  0.1426322   0.38263049]]


**Subtraction**

In [22]:
print(a-b)

[  0  -8  -8 -10]


#### Dot Product

In [23]:
print(np.dot(a,b))

364


#### Assignment 5
Perform 

1.   Muliplication
2.   Division



#### Multiplication

In [24]:
print(a*b)

[ 16  20 128 200]


#### Division

In [75]:
print(a/b)

[[  0.13374458   0.15596003   0.10933491  -0.46292609]
 [ -0.33176827  -0.4777851  -14.08049354   0.67018917]]


#### Comparison between Vectorised and  Non Vectorised Implementation in Python

In [26]:
import numpy as np
num = 500
a = np.random.random(num)
b = np.random.random(num)

#### Vectorised Implementation

In [27]:
import time
start = time.time()
c = np.dot(a,b)
end = time.time()
print(c)
print("Time taken for Verctorized Implementation  : " +  str((end -start)*1000) + 'ms')

121.6889477314456
Time taken for Verctorized Implementation  : 0.4897117614746094ms


#### Non Vectorised Implementation (Looping)

In [28]:
c =0
start = time.time()
for i in range(num):
    c += a[i]*b[i]
end = time.time()
print(c)
print("Time taken for Loop version  : " +  str((end -start)*1000) + 'ms')


121.68894773144558
Time taken for Loop version  : 0.9102821350097656ms


####  Array Slicing

In [29]:
a =np.array([1,5,2,6,3,8,9])
print(a)

[1 5 2 6 3 8 9]


In [30]:
print(a[:])   #Printing all the element

[1 5 2 6 3 8 9]


In [31]:
print(a[:3])  #Printing first three elements

[1 5 2]


In [32]:
print(a[3:])  #Starting from 3 print all

[6 3 8 9]


In [33]:
print(a[2:5]) #Starting from 2 excluding 5

[2 6 3]


In [34]:
print(a[::2]) #Starting from 0 one interval

[1 2 3 9]


In [35]:
print(a[3::2])#Starting from 3 two interval (including 3)

[6 8]


In [36]:
print(a[::-1])#Printing in reverse order

[9 8 3 6 2 5 1]


###  Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [76]:
import numpy as np
a = np.arange(5)
b = 1
print(a)
print("")

print(b)
print("")

a+b

[0 1 2 3 4]

1



array([1, 2, 3, 4, 5])

In [40]:
a = np.arange(6).reshape(2,3)
print(a)
print("")
b = np.arange(3).reshape(1,3)
print(b)
print("")
a+b

[[0 1 2]
 [3 4 5]]

[[0 1 2]]



array([[0, 2, 4],
       [3, 5, 7]])

In [42]:
a = np.arange(6).reshape(2,3)
print(a)
print("")
b = np.array([0,1]).reshape(2,1)
print(b)
print("")
a+b

[[0 1 2]
 [3 4 5]]

[[0]
 [1]]



array([[0, 1, 2],
       [4, 5, 6]])

In [44]:
a = np.arange(6).reshape(2,3)
print(a)
print("")
b = 2
print(b)
print("")
a+b

[[0 1 2]
 [3 4 5]]

2



array([[2, 3, 4],
       [5, 6, 7]])

In [46]:
a = np.array([0,3]).reshape(2,1)
print(a)
print("")
b = np.arange(3).reshape(1,3)
print(b)
print("")
a+b

[[0]
 [3]]

[[0 1 2]]



array([[0, 1, 2],
       [3, 4, 5]])

###  Lists
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.


1.   Declaring List
2.   Indentify the type
1.   Accesing list elements
2.   Printing the last element
3.   Adding the elements into the list
5.   Inserting at particular location
2.   Popping the elements from the list
5.   Clearing the list
6.   Deleting the list



In [80]:
l = [1,2,3, 'abc',True]
p = []

print(l[4])

True


In [48]:
print(type(l))

<class 'list'>


In [49]:
print(l[-1])

True


In [50]:
l.append(4)
print(l)

[1, 2, 3, 'abc', True, 4]


In [51]:
l.insert(1, 100)
print(l)

[1, 100, 2, 3, 'abc', True, 4]


In [52]:
l.pop()
print(l)

[1, 100, 2, 3, 'abc', True]


In [53]:
l.clear()
print(l)

[]


In [54]:
del l

###  Tuples
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.
#### Tuple Operations
1.   Initial element
2.   Final Element
3.   Length of tuple
4.   Delete Tuples

In [82]:
a = (1,2,3,4)
print(type(a))

<class 'tuple'>


In [83]:
print(a[-2])

3


In [57]:
print(len(a))

4


In [58]:
del a

### Difference between list and tuples

* The main difference between lists and a tuples is the fact that lists are mutable whereas tuples are immutable.
* A mutable data type means that a python object of this type can be modified.
* Immutable data type means that a python object of this type can't be modified.

In [59]:
a = ["apples", "bananas", "oranges"]

a[0] = "berries"

print(a)

['berries', 'bananas', 'oranges']


In [84]:
a = ("apples", "bananas", "oranges")

a[0] = "berries"

print(a)

TypeError: ignored

###  Dictionary
A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:


1.   Checking the presence of elements in dictionary
2.   Print Keys and Values 
3.   Print length of dictionary
4.   Getting the keys from the dictionary
7.   Updating the element in dictionary
8.   Delete

In [86]:
alpha =  {'name':['abc, def'],'roll no':[12,34]}
print(type(alpha))

<class 'dict'>


In [87]:
print(alpha)
print("")

{'name': ['abc, def'], 'roll no': [12, 34]}



In [ ]:
print(alpha.values())
print("")

In [88]:
print(alpha.keys())
print("")

dict_keys(['name', 'roll no'])



In [ ]:
print(len(alpha))

In [ ]:
print(alpha['a'])
print("")

In [ ]:
print(alpha['b'])

In [ ]:
#print(alpha['c'])

In [ ]:
alpha.update({'c':3})
print(alpha)

### Sets
A set is an unordered collection of distinct elements. As a simple example, consider the following
1.   Check the elements in sets
2.   Length of sets
3.   Add elements to sets 
4.   Remove the elements from sets
5.   Iterate with enumerate
6.   Delete

In [89]:
s = {"b","a"}
print(s)

{'b', 'a'}


In [ ]:
print("a" in s)

In [ ]:
print("z" in s)

In [90]:
s.add("c")
print(s)

{'b', 'a', 'c'}


In [91]:
s.add("b")
print(s)

{'b', 'a', 'c'}


In [ ]:
s.remove("a")
print(s)

#### Set Operation


1.   Union
2.   Intersection
3.   Difference

In [ ]:
a = {1,2,3,4}
b = {1,6,7,8}

c= a | b
print(c)
print(type(a))

In [ ]:
f= a & b
print(f)

In [ ]:
d = a-b
print(d)

In [ ]:
e = b-a
print(e)

Dataframe - Pandas

In [ ]:
import pandas as pd
df = pd.DataFrame(data=[1.,2.,3,4.1,5.6])
print(type(df))
dict1 = {'name':["aprith", "jothi"], 'roll no': [23, 16]}
df2 = pd.DataFrame(dict1)
#print(df2.head(0))
#print(df2.iloc[1])
df2 = df2.append({'name':"tarini",'roll no':45}, ignore_index=True)
print(df2)
df2.to_csv("test.csv")

Tensorflow
Tensorflow is an open-source machine learning framework that is used for complex numerical computation.
A tensor can be described as a n-dimensional numerical array. A tensor can be called a generalized matrix. 
A tensor is identified by three parameters viz., rank, shape and size. The number of dimensions of the tensor is said to be its rank. The number of columns and rows that the tensor has, is said to be its shape. And, the data type assigned to the tensor’s elements is said to be its type.


In [ ]:
import tensorflow as tf 
  
t1 = tf.constant([1., 2., 3., 4., 5.,]) 
print(t1, type(t1))
t2 = tf.linspace(1.0, 10.0, 5, "linspace_inc")
print(t2)
t2.shape
t1+t2

In [93]:
import torch as pt
import numpy as np

a = np.asarray(([1.,2.,3.,],[4.,5.,6.,],[7.,8.,9.,]))
b = pt.tensor(([1.,2.,3.,],[4.,5.,6.,],[7.,8.,9.,]))
print(type(a))
print(type(b))
print(a+b)
c = b.numpy()
#print(a+c)
d = pt.tensor(a)
print(pt.add(d,b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


TypeError: ignored